#!/bin/bash
# This script will compile a .gba, .map, and .elf from the master branch of the
# project. This version is specifically written for Arch systems or dkP's msys environment. It uses pacman rather than apt.

# If you're using a standard Debian or Ubuntu distro like Linux Lite or Mint, use the standard "makerom" script.

# Updates and upgrades the system
sudo pacman -Syu # same as "sudo apt update && sudo apt upgrade on standard distros."
# Installs dependencies
sudo pacman -S git libpng base-devel arm-none-eabi-binutils # "build-essential" is unavailable both on packages.archlinux.org and the AUR. Therefore, "base-devel" is used instead.
# clones repos
git clone git://github.com/pret/agbcc
git clone git://github.com/Rebirth-Devs/tumbledemerald
# set up agbcc
cd agbcc
sh ./build.sh
sh ./install.sh ../tumbledemerald
# final steps
cd ../tumbledemerald
make